name: Tests 
on:
  pull_request:
    branches: [ 'master' ]
  push:
    branches: [ 'master' ]
    tags: [ '*' ]

jobs:
  tests:
    name: Tests 
    runs-on: macos-11
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: 'Setup Ruby'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'

      - name: Run tests
        uses: maierj/fastlane-action@v2.2.0
        with:
          lane: 'tests'
